# 이 파일은 CI/CD 파이프라인에서 Kubernetes Secrets를 생성하기 위한 템플릿입니다.
# 실제 비밀 값을 여기에 하드코딩하지 마십시오.
#
# GitHub Actions에서 이 파일을 사용하려면:
# 1. 아래 `stringData` 섹션의 각 키에 해당하는 값을 GitHub Repository Secrets에 등록합니다.
#    (예: `INTERNAL_API_KEY`, `VELOCITY_FORWARDING_SECRET`, `SERVERTAP_API_KEY`)
# 2. CI/CD 워크플로우(.github/workflows/deploy.yml)에서 다음 명령을 사용하여
#    GitHub Secrets를 파일 내용으로 치환하고 `kubectl apply`를 실행합니다.
#
#    - name: Apply Kubernetes Secrets
#      run: |
#        sed -e "s|${{ secrets.INTERNAL_API_KEY }}|'${{ secrets.INTERNAL_API_KEY }}'|" \
#            -e "s|${{ secrets.VELOCITY_FORWARDING_SECRET }}|'${{ secrets.VELOCITY_FORWARDING_SECRET }}'|" \
#            -e "s|${{ secrets.SERVERTAP_API_KEY }}|'${{ secrets.SERVERTAP_API_KEY }}'|" \
#            secrets.template.yaml > generated-secrets.yaml
#        kubectl apply -f generated-secrets.yaml
#
# ---
#
# Base64 인코딩 대신 `stringData`를 사용하면 값을 평문으로 관리할 수 있어 편리합니다.
# Kubernetes가 자동으로 Base64로 인코딩하여 Secret을 생성합니다.
#
# 이미 생성된 Secret을 업데이트하려면 `kubectl apply` 대신 `kubectl replace` 또는
# `kubectl delete secret ...` 후 `kubectl apply`를 사용해야 할 수도 있습니다.

apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secrets
  namespace: minecraft-servers
type: Opaque
stringData:
  # .env 파일의 INTERNAL_API_KEY
  INTERNAL_API_KEY: "${{ secrets.INTERNAL_API_KEY }}"
  
  # velocity.toml의 forwarding-secret
  VELOCITY_FORWARDING_SECRET: "${{ secrets.VELOCITY_FORWARDING_SECRET }}"
  
  # 추가적으로 필요한 다른 시크릿들...
